In [1]:
import numpy as np

In [26]:
#code reference: https://stackabuse.com/levenshtein-distance-and-text-similarity-in-python/

def levenshtein(s1, s2):
    x_axis = len(s1) + 1
    y_axis = len(s2) + 1
    
    matrix = np.zeros((x_axis, y_axis))
    
    for i in range(x_axis):
        matrix[i, 0] = i
    for i in range(y_axis):
        matrix[0, i] = i
        
    for i in range(1, x_axis):
        for j in range(1, y_axis):
            if s1[i-1] == s2[j-1]:
                matrix[i, j] = min(matrix[i-1, j]+1,
                                   matrix[i, j-1]+1,
                                   matrix[i-1, j-1])
            else:
                matrix[i, j] =  min(matrix[i-1, j]+1,
                                    matrix[i, j-1]+1,
                                    matrix[i-1, j-1]+2)
    print (matrix)
    print ('The min distance between %s' %s1 + ', %s is'%s2, matrix[x_axis-1, y_axis-1] )

In [31]:
levenshtein('abbbbb', 'abc')

[[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 2.]
 [4. 3. 2. 3.]
 [5. 4. 3. 4.]
 [6. 5. 4. 5.]]
The min distance between abbbbb, abc is 5.0


In [32]:
levenshtein('intention', 'execution')

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]]
The min distance between intention, execution is 8.0


In [33]:
levenshtein('ice', 'micfffe')

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 1. 2. 3. 4. 5. 6.]
 [2. 3. 2. 1. 2. 3. 4. 5.]
 [3. 4. 3. 2. 3. 4. 5. 4.]]
The min distance between ice, micfffe is 4.0
